version: '3.4'

services:
    webapp:
        build:
            context: .
            dockerfile: Dockerfile
        image: baseapp-image
        container_name: baseapp-container
        restart: always
        command: ./startup_scripts/start-flask.sh -d 1
        depends_on:
            - database
            - worker
        environment:
            - DATABASE_URL=postgresql://postgres_user:postgres_password@database:5432
            - PORT=5000
            - SECRET_KEY
            - FLASK_DEBUG=1
            - REDIS_URL

        stdin_open: true
        tty: true
        ports:
            - "5000:5000"

        volumes:
            - .:/app

    worker:
        image: baseapp-image
        container_name: baseapp-worker
        command: ./startup_scripts/start-celery-worker.sh
        restart: on-failure
        depends_on:
            - database
            - redis
            - beat

        environment:
            - DATABASE_URL=postgresql://postgres_user:postgres_password@database:5432
            - FLASK_DEBUG=1
            - SECRET_KEY
            - REDIS_URL

    beat:
        image: baseapp-image
        container_name: baseapp-beat
        command: ./startup_scripts/start-celery-beat.sh
        restart: on-failure
        depends_on:
            - database
            - redis

        environment:
            - DATABASE_URL=postgresql://postgres_user:postgres_password@database:5432
            - FLASK_DEBUG=1
            - SECRET_KEY
            - REDIS_URL

    redis:
        image: redis:5.0
        container_name: baseapp-redis
        ports:
          - '6579:6379'
        volumes:
          - persistent_redis:/var/lib/redis/data

    database:
        environment:
          POSTGRES_USER: postgres_user
          POSTGRES_PASSWORD: postgres_password
        container_name: baseapp-database
        expose:
          - "5432"
        image: postgres:11.5
        ports:
          - "127.0.0.1:5444:5432"
        volumes:
          - persistent_database_postgres:/var/lib/postgresql/data


volumes:
  persistent_database_postgres:
  persistent_redis:
