"""fkey

Revision ID: 52793f1a856d
Revises: 678aeab9986d
Create Date: 2021-11-05 09:25:11.814832

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "52793f1a856d"
down_revision = "678aeab9986d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("plant")
    # ### end Alembic commands ###
